version: "3.9"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports: ["8000:8000"]
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    ports: ["3000:3000"]
    depends_on: [api]
